version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0

references:
  default_ruby_version: &default_ruby_version 3.1.2

executors:
  default:
    parameters:
      ruby_tag:
        description: "The `circleci/ruby` Docker image version tag."
        type: string
        default: *default_ruby_version
    docker:
      - image: cimg/ruby:<< parameters.ruby_tag >>

jobs:
  build:
    executor: default
    steps:
      - checkout
      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
  test:
    parallelism: 3
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - run:
            name: Run the Program
            command: ruby lib/main.rb
      - ruby/rspec-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
