version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2
    executor: ruby/default
    steps:
      - checkout
      - run: echo "Ruby code checked out."
      - run: echo "Bundler installing..."
      - ruby/install-deps
  test:
    docker:
      - image: cimg/ruby:3.1.2
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps
      - run: echo "Testing..."
      - run:
            name: Run the Program
            command: ruby lib/main.rb
      - ruby/rspec-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
