version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2
    executor: ruby/default
    steps:
      - checkout
      - run: echo "Ruby code checked out."
      - run: echo "Bundler installing..."
      - ruby/install-deps
      - ruby/rubocop-check:
        format: progress
        label: Inspecting with Rubocop
  test:
    docker:
      - image: cimg/ruby:3.1.2
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps
      - run: echo "Testing..."
      - ruby/rspec-test:
        include: spec/**/*_spec.rb

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
