version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2
    executor: ruby/default
    steps:
      - checkout
      - run: echo "Ruby code checked out."
      - run: echo "Bundler installing..."
      - ruby/install-deps
  test:
    docker:
      - image: cimg/ruby:3.1.2
    parallelism: 3
    steps:
      - run: echo "Testing..."
      - ruby/rspec-test


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
