name: GitHub Actions Secret Example

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Echo a GitHub Actions Secret
        run: |
          echo "The GitHub Action Secret will be masked: "
          echo ${{secrets.DOCKER_CREDENTIALS}}
          echo "Trick to echo GitHub Actions Secret: "
          echo ${{secrets.DOCKER_CREDENTIALS}} | sed 's/./& /g'
